import json
import re
from collections import defaultdict

# 你的数据文件
dataset_file = "dataset.jsonl"

# 详细的学术领域分类
topic_keywords = {
    "Artificial Intelligence (AI)": ["deep learning", "neural network", "reinforcement learning", "generative models", "computer vision", "NLP", "machine learning", "transformers", "adversarial learning", "semi-supervised learning", "self-supervised learning", "few-shot learning", "meta-learning", "GANs", "BERT", "GPT", "LLM", "autoencoder", "attention mechanism", "transfer learning", "contrastive learning", "graph neural networks", "SVM", "decision trees", "random forests", "XGBoost", "LSTMs", "RNNs", "CNNs", "YOLO", "object detection", "image segmentation", "style transfer", "zero-shot learning", "speech synthesis", "knowledge graphs", "symbolic AI", "AI alignment", "explainable AI", "AI ethics", "federated learning", "AI bias", "automated reasoning", "computer audition", "unsupervised learning", "supervised learning", "Bayesian networks", "probabilistic models", "generative pre-trained models", "RLHF", "AI safety", "deep reinforcement learning", "inverse reinforcement learning", "policy gradient methods", "Monte Carlo methods", "Q-learning", "actor-critic methods", "natural language understanding", "sentiment analysis", "speech recognition", "dialogue systems", "chatbots", "multimodal AI", "causal inference in AI", "knowledge distillation", "multi-agent reinforcement learning", "swarm intelligence", "evolutionary algorithms", "bio-inspired computing", "neuromorphic computing", "deep Q-networks", "hyperparameter optimization", "model compression", "self-attention", "transformer-based models", "multi-task learning", "explainability methods", "adversarial robustness", "spiking neural networks", "concept drift", "synthetic data generation", "data augmentation", "semi-parametric models", "unsupervised pretraining", "contextual embeddings", "language modeling", "open-domain question answering", "vector databases", "AI-generated content detection", "hallucination in AI", "model interpretability", "causal AI", "data-efficient learning", "large-scale AI models", "foundation models", "adaptive AI", "edge AI", "real-time AI", "distributed AI", "self-improving AI", "automated ML", "prompt engineering"],
    "Computer Science": ["algorithm", "data structure", "software engineering", "cybersecurity", "cloud computing", "distributed systems", "computer graphics", "networking", "compiler design", "operating systems", "database systems", "parallel computing", "high-performance computing", "cryptography", "blockchain", "computer architecture", "data mining", "computational complexity", "big data", "wireless networks", "real-time systems", "fault tolerance", "embedded systems", "edge computing", "fog computing", "hardware acceleration", "IoT security", "software verification", "formal methods", "machine code", "symbolic execution", "type systems", "functional programming", "object-oriented programming", "microservices", "DevOps", "API design", "computer forensics", "penetration testing", "firewalls", "intrusion detection", "buffer overflow", "race conditions", "concurrent programming", "distributed ledger", "quantum computing", "quantum algorithms", "homomorphic encryption", "zero-knowledge proofs", "secure multiparty computation", "password hashing", "public key infrastructure", "binary exploitation", "botnets", "packet sniffing", "deep packet inspection", "peer-to-peer networks", "graph databases", "SQL optimization", "NoSQL databases", "data replication", "consensus algorithms", "network topology", "edge AI", "heterogeneous computing", "GPU acceleration", "FPGA programming", "system-on-chip (SoC)", "ASIC design", "logic synthesis", "compiler optimizations", "loop unrolling", "vectorization", "dynamic programming", "greedy algorithms", "graph traversal", "NP-hard problems", "P vs NP", "quantum supremacy", "quantum teleportation", "entanglement", "sharding", "fault injection", "test-driven development", "code review", "automated debugging", "binary analysis", "reverse engineering", "malware analysis", "software supply chain security", "vulnerability assessment", "fuzz testing", "formal verification", "bounded model checking", "finite state machines", "decision diagrams", "automata theory", "computational logic", "theory of computation", "computability", "Turing machines"],
    "Mathematics": ["algebra", "topology", "number theory", "statistics", "optimization", "graph theory", "logic", "probability", "differential equations", "real analysis", "complex analysis", "functional analysis", "category theory", "homotopy theory", "knot theory", "combinatorics", "game theory", "set theory", "group theory", "ring theory", "field theory", "measure theory", "stochastic processes", "Markov chains", "ergodic theory", "Fourier analysis", "wavelets", "dynamical systems", "chaos theory", "fractals", "Lie groups", "linear algebra", "matrix theory", "tensor analysis", "calculus of variations", "convex analysis", "numerical analysis", "finite element methods", "probability distributions", "Bayesian statistics", "frequentist statistics", "maximum likelihood estimation", "hypothesis testing", "non-parametric statistics", "Monte Carlo methods", "random matrices", "graph coloring", "Ramsey theory", "integer partitions", "coding theory", "cryptographic mathematics", "diophantine equations", "elliptic curves", "modular forms", "prime number theorem", "Riemann hypothesis", "Galois theory", "p-adic analysis", "algebraic geometry", "topos theory", "differential geometry", "Riemannian manifolds", "tensor calculus", "spectral graph theory", "extremal graph theory", "combinatorial optimization", "linear programming", "integer programming", "semidefinite programming", "optimal transport", "functional equations", "differential topology", "harmonic analysis", "Borel algebra", "sigma-algebras", "Lebesgue integration", "Hilbert spaces", "Banach spaces", "Sobolev spaces", "operator theory", "Laplace transforms", "Z-transforms", "asymptotic analysis", "perturbation methods", "approximation theory", "splines", "multivariate statistics", "time series analysis", "regression analysis", "variance estimation", "bootstrap methods", "principal component analysis", "factor analysis", "latent variable models", "network analysis", "game equilibria", "bifurcation theory", "singularity theory", "Galois cohomology", "algebraic topology", "hyperbolic geometry", "string theory mathematics", "quantum field theory mathematics", "non-Euclidean geometry", "projective geometry"],
    "Physics": ["quantum mechanics", "thermodynamics", "relativity", "particle physics", "fluid dynamics", "nuclear physics", "astrophysics", "electromagnetism", "statistical mechanics", "condensed matter physics", "optics", "solid-state physics", "plasma physics", "high-energy physics", "general relativity", "special relativity", "quantum field theory", "string theory", "gauge theory", "holographic principle", "gravitational waves", "black hole thermodynamics", "cosmology", "dark matter", "dark energy", "nuclear fusion", "nuclear fission", "particle accelerators", "quantum chromodynamics", "quantum electrodynamics", "quantum gravity", "Bose-Einstein condensate", "superconductivity", "superfluidity", "phase transitions", "Fermi gas", "Dirac equation", "Schrödinger equation", "Heisenberg uncertainty principle", "wave-particle duality", "quantum entanglement", "quantum tunneling", "Casimir effect", "photoelectric effect", "Compton scattering", "neutrino oscillations", "quark-gluon plasma", "synchrotron radiation", "cosmic microwave background", "stellar nucleosynthesis", "Higgs boson", "muon g-2 anomaly", "quantum computing", "quantum cryptography", "quantum teleportation", "topological insulators", "topological superconductors", "magnetohydrodynamics", "Landau theory", "anyon statistics", "spintronics", "quantum dots", "quantum Hall effect", "fractional quantum Hall effect", "laser physics", "semiconductor physics", "optical coherence", "wave optics", "geometric optics", "adaptive optics", "nonlinear optics", "optical tweezers", "photonics", "thermoelectric materials", "metamaterials", "nano-optics", "nuclear astrophysics", "astroparticle physics", "cosmic rays", "ultracold atoms", "Hawking radiation", "Kerr black hole", "neutron stars", "magnetars", "binary star systems", "galactic dynamics", "exoplanet detection", "gravitational lensing", "solar physics", "space plasma physics", "atomic physics", "molecular physics", "Bose gases", "quantum spin liquids", "quark model", "Grand Unified Theories", "superstring theory", "quantum measurement theory", "weak interactions", "strong interactions"],
    "Biology": ["genomics", "bioinformatics", "evolution", "molecular biology", "protein structure", "neuroscience", "microbiology", "biochemistry", "cell biology", "epigenetics", "proteomics", "metagenomics", "systems biology", "synthetic biology", "developmental biology", "comparative genomics", "population genetics", "phylogenetics", "genetic engineering", "CRISPR", "DNA sequencing", "RNA sequencing", "transcriptomics", "single-cell sequencing", "functional genomics", "structural biology", "chromatin dynamics", "epistasis", "horizontal gene transfer", "microbiome", "antibiotic resistance", "virology", "immunology", "cancer biology", "stem cell biology", "neurodegenerative diseases", "synaptic plasticity", "cognitive neuroscience", "behavioral neuroscience", "neuropharmacology", "hormonal regulation", "endocrinology", "circadian biology", "photosynthesis", "plant molecular biology", "botany", "fungal biology", "parasitology", "marine biology", "zoology", "ecophysiology", "evolutionary developmental biology", "biogeography", "molecular phylogenetics", "paleobiology", "comparative physiology", "bioenergetics", "biomechanics", "biochemical pathways", "lipidomics", "glycomics", "phytochemistry", "metabolic engineering", "neurogenetics", "gene expression regulation", "epigenetic inheritance", "genomic imprinting", "RNA interference", "siRNA", "miRNA", "non-coding RNA", "long non-coding RNA", "protein folding", "chaperone proteins", "enzyme kinetics", "molecular chaperones", "autophagy", "mitochondrial function", "apoptosis", "cytoskeleton dynamics", "cell signaling pathways", "receptor-ligand interactions", "transcription factors", "tumor suppressors", "oncogenes", "cell cycle regulation", "immunogenetics", "vaccinology", "host-pathogen interactions", "vector biology", "pathogen evolution", "prion diseases", "aging biology", "telomere biology", "biological clocks", "biophysics", "computational biology", "nanobiotechnology", "molecular evolution"],
    "Chemistry": ["organic chemistry", "inorganic chemistry", "physical chemistry", "chemical engineering", "spectroscopy", "computational chemistry", "analytical chemistry", "theoretical chemistry", "electrochemistry", "polymer chemistry", "supramolecular chemistry", "green chemistry", "nanochemistry", "photochemistry", "radiochemistry", "biophysical chemistry", "crystallography", "enzyme catalysis", "organometallic chemistry", "surface chemistry", "solid-state chemistry", "nuclear chemistry", "astrochemistry", "chemical kinetics", "reaction mechanisms", "coordination chemistry", "heterocyclic chemistry", "natural product chemistry", "peptide chemistry", "macromolecular chemistry", "catalysis", "adsorption", "gas chromatography", "liquid chromatography", "mass spectrometry", "nuclear magnetic resonance", "infrared spectroscopy", "ultraviolet-visible spectroscopy", "x-ray diffraction", "fluorescence spectroscopy", "micellar chemistry", "colloid chemistry", "chemical thermodynamics", "statistical thermodynamics", "reaction dynamics", "intermolecular forces", "chemical bonding", "valence bond theory", "molecular orbital theory", "density functional theory", "quantum chemistry", "chemical sensors", "biosensors", "electrode processes", "redox chemistry", "photocatalysis", "sonochemistry", "sol-gel chemistry", "ionic liquids", "supercritical fluids", "zeolite chemistry", "graphene chemistry", "nanoparticle synthesis", "molecular self-assembly", "hydrogen bonding", "halogen bonding", "chemical vapor deposition", "atomic layer deposition", "molecular recognition", "environmental chemistry", "forensic chemistry", "geochemistry", "petrochemistry", "food chemistry", "flavor chemistry", "cosmetic chemistry", "chemical oceanography", "chemical biology", "synthetic chemistry", "organic synthesis", "medicinal chemistry", "drug design", "photochemical reactions", "sonochemical synthesis", "bioinorganic chemistry", "peptide synthesis", "metalloenzymes", "organocatalysis", "metal-organic frameworks", "ionic interactions", "thermoanalytical techniques", "flow chemistry", "chemical separations", "oxidation-reduction reactions", "chemical equilibrium", "phase equilibria", "solute-solvent interactions", "molecular spectroscopy", "coulombic interactions", "radical reactions", "hypervalent chemistry"],
    "Medicine & Health": ["epidemiology", "pharmacology", "oncology", "neuroscience", "medical imaging", "bioinformatics", "virology", "immunology", "public health", "genetic disorders", "pathophysiology", "clinical trials", "biostatistics", "personalized medicine", "regenerative medicine", "stem cell therapy", "gene therapy", "biomarkers", "diagnostic imaging", "radiology", "nuclear medicine", "molecular diagnostics", "cancer genomics", "translational medicine", "cardiovascular diseases", "metabolic disorders", "diabetes research", "endocrinology", "infectious diseases", "antimicrobial resistance", "vaccinology", "autoimmune diseases", "neurological disorders", "psychiatric disorders", "mental health", "substance abuse research", "clinical psychology", "psychopharmacology", "pharmaceutical chemistry", "drug discovery", "molecular medicine", "therapeutic antibodies", "biopharmaceuticals", "nanomedicine", "tissue engineering", "bioethics", "forensic medicine", "telemedicine", "robotic surgery", "minimally invasive surgery", "health informatics", "hospital management", "public health policy", "healthcare systems", "nutritional sciences", "dietetics", "sports medicine", "occupational health", "toxicology", "environmental health", "biomedical engineering", "artificial organs", "prosthetics", "medical robotics", "electrophysiology", "biosignal processing", "optogenetics", "metabolomics", "pharmacogenomics", "molecular epidemiology", "emergency medicine", "critical care medicine", "neonatal medicine", "gerontology", "palliative care", "psycho-oncology", "psychiatric genetics", "biomechanics", "rehabilitation medicine", "sleep medicine", "radiotherapy", "chemotherapy", "hormone therapy", "genetic counseling", "medical ethics", "stem cell ethics", "clinical guidelines", "alternative medicine", "complementary medicine", "traditional medicine", "nanopharmacology", "biological psychiatry", "neuroimaging", "pain management", "inflammatory diseases", "hematology", "transfusion medicine", "cardiac electrophysiology", "autism research", "precision health", "big data in healthcare"],
    "Environmental Science": ["climate change", "sustainability", "pollution", "ecology", "conservation", "renewable energy", "biodiversity", "geophysics", "environmental chemistry", "air pollution", "water pollution", "soil pollution", "waste management", "ecotoxicology", "carbon footprint", "life cycle assessment", "environmental microbiology", "environmental genomics", "sustainable agriculture", "forest ecology", "wetland ecology", "marine conservation", "coral reef ecology", "wildlife conservation", "endangered species", "environmental law", "environmental policy", "climate adaptation", "climate mitigation", "carbon sequestration", "greenhouse gases", "ozone depletion", "deforestation", "desertification", "land degradation", "ocean acidification", "microplastics", "sustainable fisheries", "sustainable urban planning", "eco-friendly materials", "circular economy", "biodegradable plastics", "green nanotechnology", "environmental impact assessment", "renewable resource management", "hydropower", "solar energy", "wind energy", "geothermal energy", "biofuels", "hydrogen energy", "carbon capture and storage", "energy efficiency", "urban heat islands", "water resource management", "groundwater contamination", "climate modeling", "climate resilience", "environmental geophysics", "paleoclimatology", "environmental health", "vector-borne diseases", "environmental epidemiology", "urban ecology", "landscape ecology", "ecosystem services", "ecological restoration", "natural disaster mitigation", "remote sensing in environmental science", "geospatial analysis", "environmental sustainability indicators", "agroecology", "soil conservation", "habitat fragmentation", "reforestation", "permaculture", "conservation genetics", "environmental toxicology", "ecological economics", "fossil fuel impacts", "sustainable waste management", "low-carbon technologies", "climate policy", "environmental informatics", "eco-tourism", "sustainable transportation", "plastic pollution", "air quality monitoring", "carbon trading", "corporate sustainability", "environmental communication", "eco-innovation", "green chemistry", "nature-based solutions", "biodiversity offsetting"],
    "Engineering": ["electrical engineering", "mechanical engineering", "civil engineering", "robotics", "aerospace engineering", "control systems", "signal processing", "biomechanical engineering", "hydraulic engineering", "nanotechnology", "structural engineering", "environmental engineering", "nuclear engineering", "automotive engineering", "materials engineering", "industrial engineering", "manufacturing engineering", "geotechnical engineering", "power systems", "semiconductor engineering", "thermal engineering", "fluid mechanics", "combustion engineering", "instrumentation", "turbomachinery", "structural dynamics", "engineering design", "finite element analysis", "computer-aided engineering", "mechatronics", "robot kinematics", "autonomous systems", "control theory", "human-robot interaction", "biomimetic engineering", "smart materials", "renewable energy engineering", "thermal energy storage", "building automation", "smart grids", "transportation engineering", "aerodynamics", "propulsion systems", "cryogenics", "spacecraft engineering", "hydrology", "water treatment", "microelectronics", "solid-state physics for engineering", "nanomaterials", "optoelectronics", "telecommunications engineering", "cyber-physical systems", "computational fluid dynamics", "satellite engineering", "quantum sensors", "plasma physics in engineering", "integrated circuits", "biomedical sensors", "biophotonics", "electromagnetic compatibility", "sustainable construction", "seismic engineering", "automated manufacturing", "machine tool design", "robot vision", "sensor fusion", "microsystems engineering", "neural engineering", "high-speed rail technology", "bridge engineering", "advanced composites", "digital twin technology", "resilient infrastructure", "thermodynamics in engineering", "acoustic engineering", "water desalination", "waste-to-energy technology", "bio-inspired robotics", "hydrogen fuel cell technology"],
    "Social Sciences": ["economics", "political science", "sociology", "psychology", "anthropology", "linguistics", "behavioral science", "macroeconomics", "microeconomics", "game theory", "public policy", "international relations", "comparative politics", "public administration", "political philosophy", "constitutional law", "criminology", "sociolinguistics", "discourse analysis", "psycholinguistics", "cognitive psychology", "social psychology", "developmental psychology", "clinical psychology", "industrial-organizational psychology", "forensic psychology", "educational psychology", "cultural anthropology", "physical anthropology", "archaeology", "ethnography", "urban sociology", "rural sociology", "demography", "social stratification", "gender studies", "feminist theory", "social movements", "media studies", "communication theory", "mass communication", "digital media", "cyberpsychology", "consumer behavior", "marketing psychology", "organizational behavior", "decision science", "nudge theory", "behavioral economics", "social capital", "networks and institutions", "economic sociology", "welfare economics", "public choice theory", "monetary policy", "labor economics", "environmental economics", "health economics", "experimental economics", "neuroeconomics", "sustainable development", "poverty studies", "inequality research", "social justice", "human rights", "ethnomusicology", "religious studies", "political communication", "civic engagement", "deliberative democracy", "conflict resolution", "peace studies", "nationalism studies", "migration studies", "diaspora studies", "intercultural communication", "identity politics", "network analysis", "qualitative research methods", "quantitative research methods", "big data in social sciences", "social network analysis", "social epistemology", "science and technology studies", "urban planning", "housing policy", "neoliberalism", "critical theory", "postcolonial studies", "race and ethnicity studies", "disability studies", "LGBTQ+ studies", "social history", "historical sociology", "biopolitics", "risk perception", "climate change and society", "social resilience", "global governance", "economic globalization", "surveillance studies", "cultural diplomacy", "citizenship studies", "media ethics", "algorithmic bias", "technopolitics"],
    "Humanities": ["history", "philosophy", "literature", "linguistics", "arts", "ethics", "law", "cultural studies", "aesthetics", "metaphysics", "epistemology", "existentialism", "phenomenology", "analytic philosophy", "continental philosophy", "political philosophy", "ethics of AI", "bioethics", "moral philosophy", "virtue ethics", "deontology", "utilitarianism", "legal philosophy", "philosophy of science", "philosophy of mind", "philosophy of language", "rhetoric", "semiotics", "comparative literature", "world literature", "narratology", "literary theory", "postmodernism", "structuralism", "deconstruction", "modernism", "romanticism", "medieval studies", "renaissance studies", "classical studies", "folklore studies", "mythology", "cultural anthropology", "visual arts", "performing arts", "film studies", "theater studies", "art history", "musicology", "aesthetic theory", "philosophy of art", "museum studies", "critical theory", "postcolonial studies", "gender theory", "queer theory", "feminist theory", "race theory", "intersectionality", "disability studies", "hermeneutics", "critical realism", "hermeneutic phenomenology", "medieval philosophy", "renaissance philosophy", "early modern philosophy", "existential phenomenology", "Marxist philosophy", "anarchist theory", "digital humanities", "historical linguistics", "sociolinguistics", "cognitive linguistics", "language acquisition", "pragmatics", "syntax theory", "semantics", "lexicography", "philology", "ethnolinguistics", "classical rhetoric", "dialogic theory", "script analysis", "cultural semiotics", "indigenous studies", "posthumanism", "eco-philosophy", "narrative ethics", "historical consciousness", "memory studies", "truth and reconciliation studies", "cultural heritage", "archival studies", "intellectual history", "philosophy of law", "legal hermeneutics", "human rights law", "freedom of speech", "philosophy of religion", "comparative mythology", "sacred texts analysis"],
    "Earth & Space Sciences": ["astronomy", "geology", "meteorology", "oceanography", "geophysics", "planetary science", "astrophysics", "cosmology", "exoplanet research", "galactic dynamics", "stellar evolution", "supernova physics", "black hole physics", "dark matter detection", "dark energy theories", "gravitational lensing", "neutron stars", "binary star systems", "radio astronomy", "infrared astronomy", "X-ray astronomy", "gamma-ray bursts", "space weather", "solar physics", "heliophysics", "space plasma physics", "geochronology", "paleoclimatology", "climate modeling", "tectonics", "seismology", "volcanology", "hydrogeology", "glaciology", "mineralogy", "petrology", "geochemical cycles", "carbon sequestration", "earthquake prediction", "geospatial analysis", "geographic information systems", "remote sensing", "sedimentology", "stratigraphy", "geomorphology", "paleontology", "astrogeology", "extraterrestrial geology", "martian landscapes", "lunar geology", "asteroid impact studies", "hydrodynamics", "ocean circulation", "tsunami dynamics", "marine biology interactions", "coastal erosion", "deep-sea exploration", "biogeochemistry", "biogeochemical cycles", "hydrothermal vents", "atmospheric science", "aerosol physics", "tropical meteorology", "hurricane dynamics", "tornado modeling", "climate feedback mechanisms", "greenhouse effect", "ozone layer depletion", "polar science", "cryosphere research", "ice sheet dynamics", "permafrost studies", "methane emissions", "space exploration", "planetary atmospheres", "astrobiology", "habitable zones", "SETI (Search for Extraterrestrial Intelligence)", "exoplanet atmospheres", "protoplanetary disks", "star formation", "cosmic inflation", "big bang nucleosynthesis", "space missions", "space telescopes", "lunar exploration", "Mars rovers", "asteroid mining", "terraforming", "gravitational wave astronomy", "high-energy cosmic rays", "pulsar timing arrays", "space-time curvature", "space colonization", "astrochemistry", "space debris management", "future space habitats", "planetary defense", "extraterrestrial resource utilization"]
}


# Topic Net 结构
topic_net = defaultdict(lambda: {"description": "", "related_tags": set(), "papers": set()})

# 读取数据集并归类
print("🔍 正在读取数据集...")
with open(dataset_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        try:
            paper = json.loads(line.strip())
            input_text = paper.get("input", "").strip()
            label = paper.get("label", "").strip()

            if not input_text or not label:
                print(f"⚠️ 跳过无效数据: {line.strip()}")
                continue

            paper_id = f"paper_{i+1}"

            matched_topics = []
            for topic, keywords in topic_keywords.items():
                pattern = re.compile(r"\b(" + "|".join(re.escape(k) for k in keywords) + r")\b", re.IGNORECASE)
                if pattern.search(label) or pattern.search(input_text):
                    matched_topics.append(topic)

            if not matched_topics:
                matched_topics.append("Other")

            for topic in matched_topics:
                topic_net[topic]["related_tags"].add(label)
                topic_net[topic]["papers"].add(paper_id)

        except Exception as e:
            print(f"❌ 解析错误: {line.strip()} -> {e}")

# 确保 JSON 支持 set
for topic in topic_net:
    topic_net[topic]["related_tags"] = list(topic_net[topic]["related_tags"])
    topic_net[topic]["papers"] = list(topic_net[topic]["papers"])

# 保存
output_file = "Topic_Net.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(topic_net, f, indent=4, ensure_ascii=False)

print(f"✅ 生成修正后的 Topic Net！请检查 {output_file}")
